---
## Ansible playbook for a CentOS 7 MySQL box for openDCIM
##
##
- name: Install MySQL
  hosts: localhost
  user: vagrant
  sudo: yes
  gather_facts: yes
  roles:
    - { role: mysql, tags: "database" }