---
## Ansible playbook for a CentOS 7 webnode box for openDCIM
- name: Install httpd + php
  hosts: localhost
  user: vagrant
  sudo: yes
  gather_facts: yes
  roles:
    - { role: httpd, tags: "webnode" }
    - { role: php, tags: "webnode" }
    - { role: opendcim, tags: "webapp" }